---

- name: get NodeJS signing key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: add NodeJS PPA
  apt_repository: repo='deb https://deb.nodesource.com/node_5.x trusty main' state=present update_cache=yes

- name: install NodeJS
  apt: name=nodejs state=present
