---

- name: download maven
  get_url:
    url: 'http://mirror.tcpdiag.net/apache/maven/maven-3/{{maven_version}}/binaries/apache-maven-{{maven_version}}-bin.tar.gz'
    dest: '/tmp/maven-{{maven_version}}-bin.tar.gz'
  register: download

- name: unpack maven
  unarchive:
    src: '/tmp/maven-{{maven_version}}-bin.tar.gz'
    dest: '/usr/local'
    copy: no
  when: download.changed

- name: install maven
  file:
    src: '/usr/local/apache-maven-{{maven_version}}'
    dest: /usr/local/maven
    state: link
  when: download.changed

- name: update $PATH
  copy:
    src: 'etc/profile.d/maven.sh'
    dest: '/etc/profile.d/maven.sh'
    mode: 0644
  when: download.changed