---

- name: get Docker key
  apt_key:
    keyserver: p80.pool.sks-keyservers.net
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: add Docker PPA
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present update_cache=yes

- name: install docker engine
  apt: name=docker-engine state=present
  notify:
    - start docker
