---

- name: download leiningen
  get_url:
    url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    dest: /tmp/lein
    checksum: 'sha1:ef30f53be163b01eeb9b533dd940b17532353337'
  register: download

- name: install leiningen
  copy:
    src: /tmp/lein
    dest: /usr/local/bin/lein
    mode: 0755
  when: download.changed
